### ISSUE TITLE
`TweakReg` crashes with not defined `self.limts`

### ISSUE THREAD

**Issue by mcara** [spacetelescope/drizzlepac#180]
When `TweakReg` is run like this:
```python
tweakreg.TweakReg('*.fits', interactive=True, use2dhist=True, see2dplot=True, residplot='both')
```
it crashes with the following error:
```python
    606                     mask = mask,
    607                     use_sharp_round = self.use_sharp_round,
--> 608                     nbright=self.limits.get('nbright')
    609                 )
    610         if len(x) == 0:

AttributeError: 'ImageCatalog' object has no attribute 'limits'
```
This is a bug introduced in https://github.com/spacetelescope/drizzlepac/pull/90

**Comment by mcara** [comment]
NOTE: this error happens _only when_ initial run of the source finding algorithm does not find any sources and then the "parent" algorithm attempts to find sources again with default settings. This second run then crashes due to the bug reported here. Therefore this bug most likely has very limited practical effect.
